### ISSUE TITLE
make fail on mac osx 

### ISSUE THREAD

**Issue by riusksk** [mothran/aflpin#2]
does aflpin support on MAC?

$sudo PIN_ROOT=/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac make   

c++ -shared -w -Wl,-exported_symbols_list -Wl,/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/source/include/pin/pintool.exp -stdlib=libstdc++    -o obj-intel64/AFLpintool.dylib obj-intel64/AFLpintool.o  -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib-ext -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/runtime/glibc -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/extras/xed2-intel64/lib -lpin -lxed -lpindwarf
clang: error: no such file or directory: 'obj-intel64/AFLpintool.o'
make: **\* [obj-intel64/AFLpintool.dylib] Error 1

**Comment by mothran** [comment]
I am not sure, I was never able to test it.  It appears that it if failing to build the ALFpintool it self.  Do you have more error logs?

**Comment by riusksk** [comment]
I make with the following cmd after del "obj-intel64/AFLpintool.o" that in the c++ build cmd:

> c++ -shared -w -Wl,-exported_symbols_list -Wl,/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/source/include/pin/pintool.exp -stdlib=libstdc++    -o obj-intel64/AFLpintool.dylib   -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib-ext -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/runtime/glibc -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/extras/xed2-intel64/lib -lpin -lxed -lpindwarf 
> **ld: library not found for -lxed**
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

beacause no such dir "/extras/xed2-intel64/lib", so I modify "/pin-3.0-76991-clang-mac/extras/xed2-intel64/lib" to "/pin-3.0-76991-clang-mac/extras/xed-intel64/lib" and rebuild:

> c++ -shared -w -Wl,-exported_symbols_list -Wl,/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/source/include/pin/pintool.exp -stdlib=libstdc++    -o obj-intel64/AFLpintool.dylib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib-ext -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/runtime/glibc -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/extras/xed-intel64/lib -lpin -lxed -lpindwarf
> **ld: library not found for -lpindwarf**
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found that no libpindwarf in pin 3.0 for mac, and it would build error if you del "-lpindwarf":

> c++ -shared -w -Wl,-exported_symbols_list -Wl,/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/source/include/pin/pintool.exp -stdlib=libstdc++    -o obj-intel64/AFLpintool.dylib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/lib-ext -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/intel64/runtime/glibc -L/Volumes/Macintosh/Users/riusksk/Reverse-Engineering/pin-3.0-76991-clang-mac/extras/xed-intel64/lib -lpin -lxed  
> Undefined symbols for architecture x86_64:
>   "_OS_DeregisterCurrentThread", referenced from:
>       LEVEL_PINCLIENT::BsdThreadTerminateProbeMode(void*, unsigned long, unsigned int, unsigned int) in libpin.a(probe_instrument_mac.os)
>   "_OS_GetKernelRelease", referenced from:
> ……
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
